apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # The port the Service exposes
      targetPort: 80 # The port on the Pod to which the Service forwards traffic
  type: NodePort
